//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetRestoSQLServeur
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.QteArticle = new HashSet<QteArticle>();
        }
    
        public int idArticle { get; set; }
        public string designationArticle { get; set; }
        public float prixArticle { get; set; }
        public string photoArticle { get; set; }
        public Nullable<int> idCatArticle { get; set; }
    
        public virtual CategorieArticle CategorieArticle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QteArticle> QteArticle { get; set; }
    }
}
