//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetRestoSQLServeur
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.QteArticle = new HashSet<QteArticle>();
        }
    
        public int numCommande { get; set; }
        public Nullable<System.DateTime> dateHeureCommance { get; set; }
        public int numTablee { get; set; }
        public int idServeur { get; set; }
        public Nullable<bool> termine { get; set; }
    
        public virtual Tablee Tablee { get; set; }
        public virtual Serveur Serveur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QteArticle> QteArticle { get; set; }
    }
}
