//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetRestoSQLServeur
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDDRestaurantEntities : DbContext
    {
        public BDDRestaurantEntities()
            : base("name=BDDRestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<CategorieArticle> CategorieArticle { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<QteArticle> QteArticle { get; set; }
        public virtual DbSet<Serveur> Serveur { get; set; }
        public virtual DbSet<Tablee> Tablee { get; set; }
    }
}
